### ISSUE TITLE
not work on Linux Mint 20.2

### ISSUE THREAD

**Issue by bug0000** [nuvious/pam-duress#26] opened 2021-10-23 19:10 UTC
When trying to enter a "password under duress", we return to the password entry window. If you enter a regular password, authentication is normal.

In the same time:
```
sudo pam_test $ USER
Credentials accepted.
Password:
Account is valid.
Authenticated
```

Configuration /etc/pam.d/common-auth 

```
auth    [success=2 default=ignore]      pam_unix.so nullok
auth    [success=1 default=ignore]      pam_duress.so nullok
auth    requisite                       pam_deny.so
auth    required                        pam_permit.so
auth    optional        pam_ecryptfs.so unwrap
auth    optional                        pam_cap.so
```
`

**Comment by nuvious** [comment] 2023-05-07 23:51
Sorry for the belated reply, but is this a password entered into a desktop envrionment password entry? Often times these use different pam configurations. The reproduction you have provided doesn't demonstrate a defect in the module itself.

**Comment by tsypanovs** [comment] 2024-05-25 16:05
I'm facing the same issue with one difference: the module doesn't work at first sign-in, however it does for the second one.

Steps to reproduce:
- install and configure the module
- check with `sudo pam_test $USER`
- power the machine off 
- power the maching on
- try to sign in with duress password
- sign-in fails
- sign in with the ordinal password
- sign out without turning the machine off
- sign in with duress password
- sign-in works

**Comment by nuvious** [comment] 2024-09-07 21:56
@bug0000 / @tsypanovs, judging from the discussion I'm going to close this issue since I think it boils down to finding the right PAM configuration to edit. The common-auth mainly works for shell login to a terminal and not windowed environments. Similarly configuration of common-auth does not work with say sudo unless the sudo pam configuration is modified.

Feel free to respond with an additional issue if you think the underlying PAM support is buggy resulting in any issues you see. Otherwise I don't intent to support distro specific configurations outside of debian common-auth but will accept pull requests from others wanting to provide guides for distro specific or desktop environment specific implementations.

**Closed by nuvious** 2024-09-07 21:56 UTC
